[package]
name = "put_the_cube_on_my_screen"
version = "0.0.3"
authors = ["Joseph Melton <jcmmelton@gmail.com>"]

[dependencies]
glium = "*"
pistoncore-glutin_window = "*"
shader_version = "*"
glutin = "*"
gl = "*"
nalgebra = "0.16"
nalgebra-glm = "0.1"
ncollide3d = "0.17"
nphysics3d = "0.9"