[package]
name = "put_the_cube_on_my_screen"
version = "0.0.3"
authors = ["Joseph Melton <jcmmelton@gmail.com>"]

[dependencies]
glium = "*"
piston = "*"
pistoncore-glutin_window = "*"
shader_version = "*"
glutin = "*"
gl = "*"
nalgebra = "0.16"
camera_controllers = "*"